<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="5" failures="1">
  <testsuite name="Root Suite" timestamp="2020-04-29T16:52:52" tests="0" file="cypress/integration/apps/navbar/NB09.js" failures="0" time="0">
  </testsuite>
  <testsuite name="9 - I can access the menu bar" timestamp="2020-04-29T16:52:52" tests="5" failures="1" time="0">
    <testcase name="9 - I can access the menu bar &quot;before all&quot; hook for &quot;NB-9-1 Should find correct menu header&quot;" time="0" classname="&quot;before all&quot; hook for &quot;NB-9-1 Should find correct menu header&quot;">
      <failure message="cy.request() failed on:

http://127.0.0.1:8080/login

The response we received from your web server was:

  &gt; 401: Unauthorized

This was considered a failure because the status code was not &apos;2xx&apos; or &apos;3xx&apos;.

If you do not want status codes to cause failures pass the option: &apos;failOnStatusCode: false&apos;

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://127.0.0.1:8080/login
Headers: {
  &quot;Connection&quot;: &quot;keep-alive&quot;,
  &quot;Content-Type&quot;: &quot;application/json&quot;,
  &quot;Authorization&quot;: &quot;Basic YWxpY2VAZXhhbXBsZS5jb206TDRiOVIwY2tzIQ==&quot;,
  &quot;user-agent&quot;: &quot;Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/81.0.4044.122 Safari/537.36&quot;,
  &quot;accept&quot;: &quot;application/json&quot;,
  &quot;accept-encoding&quot;: &quot;gzip, deflate&quot;,
  &quot;content-length&quot;: 0
}

-----------------------------------------------------------

The response we got was:

Status: 401 - Unauthorized
Headers: {
  &quot;x-powered-by&quot;: &quot;Express&quot;,
  &quot;date&quot;: &quot;Wed, 29 Apr 2020 16:52:52 GMT&quot;,
  &quot;expires&quot;: &quot;0&quot;,
  &quot;login-url&quot;: &quot;/login&quot;,
  &quot;session-token-expires-minutes&quot;: &quot;120&quot;,
  &quot;access-control-allow-origin&quot;: &quot;*&quot;,
  &quot;server&quot;: &quot;Lab7_ESP/cj/qa882&quot;,
  &quot;access-control-allow-credentials&quot;: &quot;true&quot;,
  &quot;server-execution-time-ms&quot;: &quot;520.6890106201172&quot;,
  &quot;connection&quot;: &quot;close&quot;,
  &quot;access-control-allow-headers&quot;: &quot;access-control-allow-origin,authorization,content-type&quot;,
  &quot;content-type&quot;: &quot;application/json; charset=UTF-8&quot;,
  &quot;pragma&quot;: &quot;no-cache&quot;,
  &quot;access-control-allow-methods&quot;: &quot;GET, PUT, POST, DELETE, OPTIONS&quot;,
  &quot;cache-control&quot;: &quot;no-cache, no-store&quot;,
  &quot;content-length&quot;: &quot;57&quot;,
  &quot;vary&quot;: &quot;Accept-Encoding&quot;,
  &quot;x-server&quot;: &quot;server_8003&quot;,
  &quot;x-frame-options&quot;: &quot;sameorigin&quot;,
  &quot;x-content-type-options&quot;: &quot;nosniff&quot;,
  &quot;x-xss-protection&quot;: &quot;1; mode=block&quot;,
  &quot;set-cookie&quot;: [
    &quot;l7_esp_server_id=; Expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/&quot;
  ]
}
Body: {
  &quot;error&quot;: &quot;A user with those credentials was not found.&quot;
}


Because this error occurred during a &apos;before all&apos; hook we are skipping the remaining tests in the current suite: &apos;9 - I can access the menu bar&apos;" type="CypressError"><![CDATA[CypressError: cy.request() failed on:

http://127.0.0.1:8080/login

The response we received from your web server was:

  > 401: Unauthorized

This was considered a failure because the status code was not '2xx' or '3xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://127.0.0.1:8080/login
Headers: {
  "Connection": "keep-alive",
  "Content-Type": "application/json",
  "Authorization": "Basic YWxpY2VAZXhhbXBsZS5jb206TDRiOVIwY2tzIQ==",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/81.0.4044.122 Safari/537.36",
  "accept": "application/json",
  "accept-encoding": "gzip, deflate",
  "content-length": 0
}

-----------------------------------------------------------

The response we got was:

Status: 401 - Unauthorized
Headers: {
  "x-powered-by": "Express",
  "date": "Wed, 29 Apr 2020 16:52:52 GMT",
  "expires": "0",
  "login-url": "/login",
  "session-token-expires-minutes": "120",
  "access-control-allow-origin": "*",
  "server": "Lab7_ESP/cj/qa882",
  "access-control-allow-credentials": "true",
  "server-execution-time-ms": "520.6890106201172",
  "connection": "close",
  "access-control-allow-headers": "access-control-allow-origin,authorization,content-type",
  "content-type": "application/json; charset=UTF-8",
  "pragma": "no-cache",
  "access-control-allow-methods": "GET, PUT, POST, DELETE, OPTIONS",
  "cache-control": "no-cache, no-store",
  "content-length": "57",
  "vary": "Accept-Encoding",
  "x-server": "server_8003",
  "x-frame-options": "sameorigin",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "set-cookie": [
    "l7_esp_server_id=; Expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/"
  ]
}
Body: {
  "error": "A user with those credentials was not found."
}


Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: '9 - I can access the menu bar'
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:127890:21
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>