<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="132.132" tests="3" failures="1">
  <testsuite name="Root Suite" timestamp="2020-06-26T16:53:38" tests="0" file="cypress/integration/apps/sample_sets/LM58h.js" failures="0" time="0">
  </testsuite>
  <testsuite name="58h - archive worksheets with multiple sample protocols" timestamp="2020-06-26T16:53:38" tests="3" failures="1" time="132.132">
    <testcase name="58h - archive worksheets with multiple sample protocols LM-58h-1 - Archive after all samples are complete" time="56.942" classname="LM-58h-1 - Archive after all samples are complete">
    </testcase>
    <testcase name="58h - archive worksheets with multiple sample protocols LM-58h-2 - Archive after all samples fail in second protocol" time="22.944" classname="LM-58h-2 - Archive after all samples fail in second protocol">
    </testcase>
    <testcase name="58h - archive worksheets with multiple sample protocols LM-58h-3 - Archive after all samples fail in third protocol" time="26.123" classname="LM-58h-3 - Archive after all samples fail in third protocol">
    </testcase>
    <testcase name="58h - archive worksheets with multiple sample protocols &quot;after all&quot; hook for &quot;LM-58h-3 - Archive after all samples fail in third protocol&quot;" time="26.123" classname="&quot;after all&quot; hook for &quot;LM-58h-3 - Archive after all samples fail in third protocol&quot;">
      <failure message="cy.exec(&apos;esp -s -P 443 -H chris.test.l7informatics.com -u admin@localhost -p L4b7R0cks! seed -f -d cypress/fixtures/apps/sample_sets/LM58hseed.yml&apos;) failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-06-26 11:55:27,653:Dropping SampleSheet: LM58-x h
INFO:root:2020-06-26 11:55:27,811:Dropping Experiment: LM58h-x
INFO:root:2020-06-26 11:55:28,928:Dropping Experiment: LM58h-1
Traceb...

Because this error occurred during a &apos;after all&apos; hook we are skipping the remaining tests in the current suite: &apos;58h - archive worksheets wi...&apos;" type="CypressError"><![CDATA[CypressError: cy.exec('esp -s -P 443 -H chris.test.l7informatics.com -u admin@localhost -p L4b7R0cks! seed -f -d cypress/fixtures/apps/sample_sets/LM58hseed.yml') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-06-26 11:55:27,653:Dropping SampleSheet: LM58-x h
INFO:root:2020-06-26 11:55:27,811:Dropping Experiment: LM58h-x
INFO:root:2020-06-26 11:55:28,928:Dropping Experiment: LM58h-1
Traceb...

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite: '58h - archive worksheets wi...'
    at cypressErr (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:138017:3)
    at https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:125593:26
    at tryCatcher (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>