<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="40.44999999999999" tests="5" failures="1">
  <testsuite name="Root Suite" timestamp="2020-07-10T21:28:11" tests="0" file="cypress/integration/apps/lims/LM35.js" failures="0" time="0">
  </testsuite>
  <testsuite name="35 - I can see worksheet state in card and list view" timestamp="2020-07-10T21:28:11" tests="5" failures="1" time="40.44999999999999">
    <testcase name="35 - I can see worksheet state in card and list view LM-35-1 Should find empty worksheet" time="30.116" classname="LM-35-1 Should find empty worksheet">
    </testcase>
    <testcase name="35 - I can see worksheet state in card and list view LM-35-2 Should find loading worksheet" time="3.229" classname="LM-35-2 Should find loading worksheet">
    </testcase>
    <testcase name="35 - I can see worksheet state in card and list view LM-35-3 Should find running worksheet" time="1.979" classname="LM-35-3 Should find running worksheet">
    </testcase>
    <testcase name="35 - I can see worksheet state in card and list view LM-35-4 Should find done worksheet" time="1.8" classname="LM-35-4 Should find done worksheet">
    </testcase>
    <testcase name="35 - I can see worksheet state in card and list view LM-35-5 Should find failed worksheet" time="1.663" classname="LM-35-5 Should find failed worksheet">
    </testcase>
    <testcase name="35 - I can see worksheet state in card and list view &quot;after all&quot; hook for &quot;LM-35-5 Should find failed worksheet&quot;" time="1.663" classname="&quot;after all&quot; hook for &quot;LM-35-5 Should find failed worksheet&quot;">
      <failure message="Execution of &quot;esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/lims/LM35seed.yml&quot; failed
        Exit code: 1
        Stdout:

        Stderr:
INFO:root:2020-07-10 16:28:52,218:Dropping SampleSheet: LM35-2
INFO:root:2020-07-10 16:28:52,280:Dropping Experiment: LM35-2
INFO:root:2020-07-10 16:28:53,034:Dropping SampleSheet: LM35-3
INFO:root:2020-07-10 16:28:53,096:Dropping Experiment: LM35-3
INFO:root:2020-07-10 16:28:53,690:Dropping SampleSheet: LM35-4
INFO:root:2020-07-10 16:28:53,751:Dropping Experiment: LM35-4
Traceback (most recent call last):
  File &quot;/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp&quot;, line 11, in &lt;module&gt;
    load_entry_point(&apos;espclient&apos;, &apos;console_scripts&apos;, &apos;esp&apos;)()
  File &quot;/Users/cj/bitrepos/esp/client/esp/__main__.py&quot;, line 662, in main
    args.func(args)
  File &quot;/Users/cj/bitrepos/esp/client/esp/__main__.py&quot;, line 64, in _
    return func(args)
  File &quot;/Users/cj/bitrepos/esp/client/esp/__main__.py&quot;, line 308, in seed
    model.drop(deep=args.deep)
  File &quot;/Users/cj/bitrepos/esp/client/esp/models/project.py&quot;, line 977, in drop
    if self.state not in [&apos;pending&apos;, &apos;queued&apos;] and self.sheet.exists():
  File &quot;/Users/cj/bitrepos/esp/develop/bin/.venv/lib/python3.7/site-packages/gems/decorators.py&quot;, line 102, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File &quot;/Users/cj/bitrepos/esp/client/esp/models/project.py&quot;, line 1030, in sheet
    raise AssertionError(&apos;Experiment must be submitted to access sample sheet!&apos;)
AssertionError: Experiment must be submitted to access sample sheet!

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `35 - I can see worksheet st...`" type="Error"><![CDATA[Error: Execution of "esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/lims/LM35seed.yml" failed
        Exit code: 1
        Stdout:

        Stderr:
INFO:root:2020-07-10 16:28:52,218:Dropping SampleSheet: LM35-2
INFO:root:2020-07-10 16:28:52,280:Dropping Experiment: LM35-2
INFO:root:2020-07-10 16:28:53,034:Dropping SampleSheet: LM35-3
INFO:root:2020-07-10 16:28:53,096:Dropping Experiment: LM35-3
INFO:root:2020-07-10 16:28:53,690:Dropping SampleSheet: LM35-4
INFO:root:2020-07-10 16:28:53,751:Dropping Experiment: LM35-4
Traceback (most recent call last):
  File "/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp", line 11, in <module>
    load_entry_point('espclient', 'console_scripts', 'esp')()
  File "/Users/cj/bitrepos/esp/client/esp/__main__.py", line 662, in main
    args.func(args)
  File "/Users/cj/bitrepos/esp/client/esp/__main__.py", line 64, in _
    return func(args)
  File "/Users/cj/bitrepos/esp/client/esp/__main__.py", line 308, in seed
    model.drop(deep=args.deep)
  File "/Users/cj/bitrepos/esp/client/esp/models/project.py", line 977, in drop
    if self.state not in ['pending', 'queued'] and self.sheet.exists():
  File "/Users/cj/bitrepos/esp/develop/bin/.venv/lib/python3.7/site-packages/gems/decorators.py", line 102, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/cj/bitrepos/esp/client/esp/models/project.py", line 1030, in sheet
    raise AssertionError('Experiment must be submitted to access sample sheet!')
AssertionError: Experiment must be submitted to access sample sheet!

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `35 - I can see worksheet st...`
    at Context.eval (http://127.0.0.1:8080/__cypress/tests?p=cypress/support/index.js:739:13)]]></failure>
    </testcase>
  </testsuite>
</testsuites>