<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="25.483000000000004" tests="6" failures="1">
  <testsuite name="Root Suite" timestamp="2020-03-29T00:37:49" tests="0" file="cypress/integration/apps/projects/PR18.js" failures="0" time="0">
  </testsuite>
  <testsuite name="18 - I can list experiments" timestamp="2020-03-29T00:37:49" tests="6" failures="1" time="25.483000000000004">
    <testcase name="18 - I can list experiments PR-18-1 Should show correct experiment names" time="11.773" classname="PR-18-1 Should show correct experiment names">
    </testcase>
    <testcase name="18 - I can list experiments PR-18-2 Should show correct status" time="3.49" classname="PR-18-2 Should show correct status">
    </testcase>
    <testcase name="18 - I can list experiments PR-18-3 Should see correct workflow for each experiment" time="1.99" classname="PR-18-3 Should see correct workflow for each experiment">
    </testcase>
    <testcase name="18 - I can list experiments PR-18-4 Should show correct number of samples" time="2.129" classname="PR-18-4 Should show correct number of samples">
    </testcase>
    <testcase name="18 - I can list experiments PR-18-5 Should show correct project" time="2.019" classname="PR-18-5 Should show correct project">
    </testcase>
    <testcase name="18 - I can list experiments PR-18-6 Should show correct owner" time="2.041" classname="PR-18-6 Should show correct owner">
    </testcase>
    <testcase name="18 - I can list experiments &quot;after all&quot; hook for &quot;PR-18-6 Should show correct owner&quot;" time="2.041" classname="&quot;after all&quot; hook for &quot;PR-18-6 Should show correct owner&quot;">
      <failure message="cy.exec(&apos;esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/projects/PR18seed.yml&apos;) failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 19:38:14,432:Dropping Experiment: PR18 one
INFO:root:2020-03-28 19:38:15,424:Saving data in Experiment PR18 two for Protocol: Simple Protocol.
Traceback (most recent call last)...

Because this error occurred during a &apos;after all&apos; hook we are skipping the remaining tests in the current suite: &apos;18 - I can list experiments&apos;" type="CypressError"><![CDATA[CypressError: cy.exec('esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/projects/PR18seed.yml') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 19:38:14,432:Dropping Experiment: PR18 one
INFO:root:2020-03-28 19:38:15,424:Saving data in Experiment PR18 two for Protocol: Simple Protocol.
Traceback (most recent call last)...

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite: '18 - I can list experiments'
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:125593:26
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>